[[redirects]]
from = "/proxy/*"
  to = "https://naveropenapi.apigw.ntruss.com/:splat" 
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
