[[redirects]]
from = "/proxy/*"
  to = "https://naveropenapi.apigw.ntruss.com/:splat"  
  status = 200
  force = true
  
[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"
