export { ReactComponent as LogoImage } from './logo.svg'
export { ReactComponent as CheckIcon } from './check.svg'
export { ReactComponent as HalfWaterDrop } from './halfWaterDrop.svg'
export { ReactComponent as WaterDrop } from './waterDrop.svg'
export { ReactComponent as EmptyWaterDrop } from './emptyWaterDrop.svg'
